# Generated by Django 4.1.2 on 2022-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saja', '0003_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidadStock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
