# Generated by Django 4.1.2 on 2022-10-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saja', '0005_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompra', models.IntegerField()),
                ('idProducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('pagoTotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
