# Generated by Django 4.1.2 on 2022-10-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saja', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompra', models.IntegerField()),
                ('nombreCliente', models.CharField(max_length=255)),
                ('idCliente', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('idProducto', models.IntegerField()),
                ('pagoTotal', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
